# External gems
gems:
  # - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap

exclude:
  - "/vendor/"

# Site settings
title: The Nonprofit MBA
subtitle: "Resources for the Effective Nonprofit Manager"
email: jp@nonprofit.mba
name: JP Molina
description: > 
  Useful knowledge and resources for nonprofit managers
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://nonprofit.mba" # the base hostname & protocol for your site
cover: "assets/header_image.jpg"
logo: "assets/logo.png"
author: JP Molina

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
# jekyll-archives: 
#   enabled: 
#     - categories
#     - tags
#   layout: 'archive'
#   permalinks:
#     category: '/category/:name/'
#     tag: '/tag/:name/'

# Set to true the value of 'subscribe' if you have code for an embedded form 
# from a subscription service like Mailchimp. Create a file with your embedding code
# named "subscribe.html" and save it in _includes. Your form will appear in every post
# after the rss and share sections, except in posts where subscribe_disabled: true 
# is in the front matter.
subscribe: true

# Disqus comments 
disqus_shortname: npman

# Google analytics
ga_tracking_id: "UA-76474260-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: essays
    desc: "The main dish. The good stuff. Read these."

  - cat: til
    desc: "Today I Learned..."

  - cat: notes
    desc: "A collection of snippets of knowledge to build on."
    
  - cat: books
    desc: "The most important ideas in key books for nonprofit managers."

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
# 
# Example:
# 
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Twitter
    icon: twitter
    username: 
    url: 
    desc: Follow me on Twitter
    share: false

  - name: Facebook
    icon: facebook
    username: 
    url: 
    desc: Friend me on Facebook
    share: false

  - name: GitHub
    icon: github
    username: 
    url: 
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Juan Pablo Molina
    url: https://www.linkedin.com/in/juanpablomolinaberrizbeitia
    desc: Connect with me on LinkedIn
    share: true

  - name: Google+
    icon: google-plus
    username: 
    url: 
    desc: Add me to your Circles
    share: false

  - name: YouTube
    icon: youtube
    username: 
    url: 
    desc: Subscribe on YouTube
    share: false

  - name: Instagram
    icon: instagram
    username: 
    url: 
    desc: Follow me on Instagram
    share: false

  - name: Pinterest
    icon: pinterest
    username: 
    url: 
    desc: Follow me on Pinterest
    share: false

  - name: SoundCloud
    icon: soundcloud
    username: 
    url: 
    desc: Follow me on SoundCloud
    share: false

  - name: Tumblr
    icon: tumblr
    username: 
    url: 
    desc: Follow me on Tumblr
    share: false

  - name: Steam
    icon: steam
    username: 
    url: 
    desc: Friend me on Steam
    share: false

  - name: Dribbble
    icon: dribbble
    username: 
    url: 
    desc: Follow me on Dribble
    share: false

  - name: Vimeo
    icon: vimeo-square
    username: 
    url: 
    desc: Follow me on Vimeo
    share: false

  - name: Vine
    icon: vine
    username: 
    url: 
    desc: Follow me on Vine
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "assets/logo.png"

    os_repo: "https://github.com/nonprofitmba/centrarium"
    os_rcs_type: "git"
    os_src: "git@github.com:nonprofitmba/centrarium.git"
